# Generated by Django 3.0.6 on 2025-03-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logistica',
            options={'permissions': [('puede_ingresar', 'Puede Ingresar'), ('puede_ver', 'Puede Ver'), ('puede_insertar', 'Puede Insertar'), ('puede_modificar', 'Puede Modificar'), ('puede_borrar', 'Puede Borrar'), ('puede_autorizar', 'Puede Autorizar HE'), ('puede_denegar', 'Puede Denegar HE'), ('puede_restaurar', 'Puede Restaurar HE'), ('puede_dar_baja', 'Puede Dar de Baja PF')]},
        ),
    ]
