# Generated by Django 3.0.6 on 2023-09-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('puede_ingresar', 'Puede Ingresar'), ('puede_ver', 'Puede Ver'), ('puede_insertar', 'Puede Insertar'), ('puede_modificar', 'Puede Modificar'), ('puede_borrar', 'Puede Borrar')],
            },
        ),
    ]
