# Generated by Django 3.0.6 on 2024-02-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frio',
            options={'permissions': [('puede_ingresar', 'Puede Ingresar'), ('puede_ver', 'Puede Ver'), ('puede_insertar', 'Puede Insertar'), ('puede_modificar', 'Puede Modificar'), ('puede_borrar', 'Puede Borrar'), ('puede_autorizar', 'Puede Autorizar HE'), ('puede_denegar', 'Puede Denegar HE')]},
        ),
    ]
