# Generated by Django 3.0.6 on 2024-01-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bascula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bascula',
            options={'permissions': [('puede_ingresar', 'Puede Ingresar'), ('puede_ver', 'Puede Ver'), ('puede_insertar', 'Puede Insertar'), ('puede_modificar', 'Puede Modificar'), ('puede_borrar', 'Puede Borrar'), ('puede_crear_remito', 'Puede Crear Remito')]},
        ),
    ]
