# Generated by Django 3.0.6 on 2023-09-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TresAses', '0002_modulo_empaque'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingreso_Modulo_Empaque',
        ),
        migrations.DeleteModel(
            name='Modulo_Empaque',
        ),
    ]
