# Generated by Django 3.0.6 on 2023-09-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TresAses', '0003_auto_20230919_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaContraseñas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=45)),
                ('ContraseñaVieja', models.CharField(max_length=45)),
                ('ContraseñaNueva', models.CharField(max_length=45)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CapturaErroresSQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aplicacion', models.CharField(max_length=45)),
                ('Funcion', models.CharField(max_length=45)),
                ('Usuario', models.CharField(max_length=45)),
                ('Error', models.TextField()),
                ('Fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CapturaRegistros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aplicacion', models.CharField(max_length=45)),
                ('Funcion', models.CharField(max_length=45)),
                ('Usuario', models.CharField(max_length=45)),
                ('Realiza', models.CharField(max_length=45)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
    ]
