# Generated by Django 3.0.6 on 2023-09-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TresAses', '0004_capturacontraseñas_capturaerroressql_capturaregistros'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturaregistros',
            name='Accion',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
